
// Code generated by stanc v2.29.0
#include <stan/model/model_header.hpp>
namespace model2_student_t_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 43> locations_array__ = 
{" (found before start of program)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 20, column 2 to column 13)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 21, column 2 to column 17)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 22, column 2 to column 17)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 23, column 2 to column 18)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 24, column 2 to column 22)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 25, column 2 to column 29)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 29, column 2 to column 38)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 51, column 2 to column 15)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 52, column 2 to column 25)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 53, column 2 to column 21)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 54, column 2 to column 20)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 55, column 2 to column 20)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 58, column 4 to line 61, column 44)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 63, column 4 to column 54)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 64, column 4 to column 43)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 65, column 4 to column 33)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 66, column 4 to column 69)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 57, column 17 to line 67, column 3)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 57, column 2 to line 67, column 3)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 33, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 33, column 2 to line 36, column 44)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 39, column 2 to column 38)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 40, column 2 to column 34)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 41, column 2 to column 35)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 42, column 2 to column 36)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 43, column 2 to column 33)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 44, column 2 to column 31)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 47, column 2 to column 38)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 12, column 2 to column 17)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 13, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 13, column 2 to column 21)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 14, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 14, column 2 to column 29)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 15, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 15, column 2 to column 30)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 16, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 16, column 2 to column 26)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 51, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 52, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 53, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 54, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/model2_student_t.stan', line 55, column 9 to column 10)"};




class model2_student_t_model final : public model_base_crtp<model2_student_t_model> {

 private:
  int N;
  Eigen::Matrix<double, -1, 1> log_time__;
  Eigen::Matrix<double, -1, 1> distance_log_std__;
  Eigen::Matrix<double, -1, 1> elevation_log_std__;
  Eigen::Matrix<double, -1, 1> steepness_std__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> log_time{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> distance_log_std{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> elevation_log_std{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> steepness_std{nullptr, 0};
 
 public:
  ~model2_student_t_model() { }
  
  inline std::string model_name() const final { return "model2_student_t_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.0", "stancflags = "};
  }
  
  
  model2_student_t_model(stan::io::var_context& context__,
                         unsigned int random_seed__ = 0,
                         std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "model2_student_t_model_namespace::model2_student_t_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 29;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      
      current_statement__ = 29;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("log_time", "N", N);
      current_statement__ = 31;
      context__.validate_dims("data initialization","log_time","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      log_time__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&log_time) Eigen::Map<Eigen::Matrix<double, -1, 1>>(log_time__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> log_time_flat__;
        current_statement__ = 31;
        log_time_flat__ = context__.vals_r("log_time");
        current_statement__ = 31;
        pos__ = 1;
        current_statement__ = 31;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 31;
          stan::model::assign(log_time, log_time_flat__[(pos__ - 1)],
            "assigning variable log_time", stan::model::index_uni(sym1__));
          current_statement__ = 31;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 32;
      stan::math::validate_non_negative_index("distance_log_std", "N", N);
      current_statement__ = 33;
      context__.validate_dims("data initialization","distance_log_std",
          "double", std::vector<size_t>{static_cast<size_t>(N)});
      distance_log_std__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&distance_log_std) Eigen::Map<Eigen::Matrix<double, -1, 1>>(distance_log_std__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> distance_log_std_flat__;
        current_statement__ = 33;
        distance_log_std_flat__ = context__.vals_r("distance_log_std");
        current_statement__ = 33;
        pos__ = 1;
        current_statement__ = 33;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 33;
          stan::model::assign(distance_log_std,
            distance_log_std_flat__[(pos__ - 1)],
            "assigning variable distance_log_std", stan::model::index_uni(sym1__));
          current_statement__ = 33;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 34;
      stan::math::validate_non_negative_index("elevation_log_std", "N", N);
      current_statement__ = 35;
      context__.validate_dims("data initialization","elevation_log_std",
          "double", std::vector<size_t>{static_cast<size_t>(N)});
      elevation_log_std__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&elevation_log_std) Eigen::Map<Eigen::Matrix<double, -1, 1>>(elevation_log_std__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> elevation_log_std_flat__;
        current_statement__ = 35;
        elevation_log_std_flat__ = context__.vals_r("elevation_log_std");
        current_statement__ = 35;
        pos__ = 1;
        current_statement__ = 35;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 35;
          stan::model::assign(elevation_log_std,
            elevation_log_std_flat__[(pos__ - 1)],
            "assigning variable elevation_log_std", stan::model::index_uni(sym1__));
          current_statement__ = 35;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 36;
      stan::math::validate_non_negative_index("steepness_std", "N", N);
      current_statement__ = 37;
      context__.validate_dims("data initialization","steepness_std","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      steepness_std__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&steepness_std) Eigen::Map<Eigen::Matrix<double, -1, 1>>(steepness_std__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> steepness_std_flat__;
        current_statement__ = 37;
        steepness_std_flat__ = context__.vals_r("steepness_std");
        current_statement__ = 37;
        pos__ = 1;
        current_statement__ = 37;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 37;
          stan::model::assign(steepness_std,
            steepness_std_flat__[(pos__ - 1)],
            "assigning variable steepness_std", stan::model::index_uni(sym1__));
          current_statement__ = 37;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 38;
      stan::math::validate_non_negative_index("mu", "N", N);
      current_statement__ = 39;
      stan::math::validate_non_negative_index("log_time_rep", "N", N);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("time_rep", "N", N);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("time_mu", "N", N);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("log_lik", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1 + 1;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model2_student_t_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_dist = DUMMY_VAR__;
      current_statement__ = 2;
      beta_dist = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_elev = DUMMY_VAR__;
      current_statement__ = 3;
      beta_elev = in__.template read<local_scalar_t__>();
      local_scalar_t__ beta_steep = DUMMY_VAR__;
      current_statement__ = 4;
      beta_steep = in__.template read<local_scalar_t__>();
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 5;
      sigma = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      local_scalar_t__ nu_minus_two = DUMMY_VAR__;
      current_statement__ = 6;
      nu_minus_two = in__.template read_constrain_lb<local_scalar_t__, 
                       jacobian__>(0, lp__);
      local_scalar_t__ nu = DUMMY_VAR__;
      current_statement__ = 7;
      nu = (2 + nu_minus_two);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "nu", nu, 2);
      {
        current_statement__ = 20;
        stan::math::validate_non_negative_index("mu", "N", N);
        Eigen::Matrix<local_scalar_t__, -1, 1> mu =
           Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(N, DUMMY_VAR__);
        current_statement__ = 21;
        stan::model::assign(mu,
          stan::math::add(
            stan::math::add(
              stan::math::add(alpha,
                stan::math::multiply(beta_dist, distance_log_std)),
              stan::math::multiply(beta_elev, elevation_log_std)),
            stan::math::multiply(beta_steep, steepness_std)),
          "assigning variable mu");
        current_statement__ = 22;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(alpha, stan::math::log(10), 0.5));
        current_statement__ = 23;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(beta_dist, 0.6, 0.3));
        current_statement__ = 24;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(beta_elev, 0.2, 0.25));
        current_statement__ = 25;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(beta_steep, 0.15, 0.25));
        current_statement__ = 26;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(sigma, 0, 0.35));
        current_statement__ = 27;
        lp_accum__.add(stan::math::gamma_lpdf<propto__>(nu_minus_two, 2, 0.1));
        current_statement__ = 28;
        lp_accum__.add(
          stan::math::student_t_lpdf<propto__>(log_time, nu, mu, sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "model2_student_t_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha = in__.template read<local_scalar_t__>();
      double beta_dist = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      beta_dist = in__.template read<local_scalar_t__>();
      double beta_elev = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      beta_elev = in__.template read<local_scalar_t__>();
      double beta_steep = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      beta_steep = in__.template read<local_scalar_t__>();
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      sigma = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      double nu_minus_two = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      nu_minus_two = in__.template read_constrain_lb<local_scalar_t__, 
                       jacobian__>(0, lp__);
      double nu = std::numeric_limits<double>::quiet_NaN();
      out__.write(alpha);
      out__.write(beta_dist);
      out__.write(beta_elev);
      out__.write(beta_steep);
      out__.write(sigma);
      out__.write(nu_minus_two);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 7;
      nu = (2 + nu_minus_two);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "nu", nu, 2);
      if (emit_transformed_parameters__) {
        out__.write(nu);
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      Eigen::Matrix<double, -1, 1> mu =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> log_time_rep =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> time_rep =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> time_mu =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> log_lik =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 19;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 13;
        stan::model::assign(mu,
          (((alpha +
              (beta_dist *
                stan::model::rvalue(distance_log_std, "distance_log_std",
                  stan::model::index_uni(i)))) +
             (beta_elev *
               stan::model::rvalue(elevation_log_std, "elevation_log_std",
                 stan::model::index_uni(i)))) +
            (beta_steep *
              stan::model::rvalue(steepness_std, "steepness_std",
                stan::model::index_uni(i)))),
          "assigning variable mu", stan::model::index_uni(i));
        current_statement__ = 14;
        stan::model::assign(log_time_rep,
          stan::math::student_t_rng(nu,
            stan::model::rvalue(mu, "mu", stan::model::index_uni(i)), sigma,
            base_rng__),
          "assigning variable log_time_rep", stan::model::index_uni(i));
        current_statement__ = 15;
        stan::model::assign(time_rep,
          stan::math::exp(
            stan::model::rvalue(log_time_rep, "log_time_rep",
              stan::model::index_uni(i))),
          "assigning variable time_rep", stan::model::index_uni(i));
        current_statement__ = 16;
        stan::model::assign(time_mu,
          stan::math::exp(
            stan::model::rvalue(mu, "mu", stan::model::index_uni(i))),
          "assigning variable time_mu", stan::model::index_uni(i));
        current_statement__ = 17;
        stan::model::assign(log_lik,
          stan::math::student_t_lpdf<false>(
            stan::model::rvalue(log_time, "log_time",
              stan::model::index_uni(i)), nu,
            stan::model::rvalue(mu, "mu", stan::model::index_uni(i)), sigma),
          "assigning variable log_lik", stan::model::index_uni(i));
      }
      out__.write(mu);
      out__.write(log_time_rep);
      out__.write(time_rep);
      out__.write(time_mu);
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ alpha = DUMMY_VAR__;
      alpha = in__.read<local_scalar_t__>();
      out__.write(alpha);
      local_scalar_t__ beta_dist = DUMMY_VAR__;
      beta_dist = in__.read<local_scalar_t__>();
      out__.write(beta_dist);
      local_scalar_t__ beta_elev = DUMMY_VAR__;
      beta_elev = in__.read<local_scalar_t__>();
      out__.write(beta_elev);
      local_scalar_t__ beta_steep = DUMMY_VAR__;
      beta_steep = in__.read<local_scalar_t__>();
      out__.write(beta_steep);
      local_scalar_t__ sigma = DUMMY_VAR__;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
      local_scalar_t__ nu_minus_two = DUMMY_VAR__;
      nu_minus_two = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, nu_minus_two);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"alpha", "beta_dist", "beta_elev",
      "beta_steep", "sigma", "nu_minus_two", "nu", "mu", "log_time_rep",
      "time_rep", "time_mu", "log_lik"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "beta_dist");
    param_names__.emplace_back(std::string() + "beta_elev");
    param_names__.emplace_back(std::string() + "beta_steep");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "nu_minus_two");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "nu");
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_time_rep" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "time_rep" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "time_mu" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "beta_dist");
    param_names__.emplace_back(std::string() + "beta_elev");
    param_names__.emplace_back(std::string() + "beta_steep");
    param_names__.emplace_back(std::string() + "sigma");
    param_names__.emplace_back(std::string() + "nu_minus_two");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "nu");
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_time_rep" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "time_rep" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "time_mu" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_lik" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_dist\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_elev\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_steep\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu_minus_two\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_time_rep\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"time_rep\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"time_mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_dist\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_elev\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"beta_steep\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu_minus_two\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"nu\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_time_rep\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"time_rep\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"time_mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((1 + 1) + 1) + 1) + 1) + 1);
      const size_t num_transformed = 1;
      const size_t num_gen_quantities = 
  ((((N + N) + N) + N) + N);
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((1 + 1) + 1) + 1) + 1) + 1);
      const size_t num_transformed = 1;
      const size_t num_gen_quantities = 
  ((((N + N) + N) + N) + N);
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 6> names__{"alpha", "beta_dist",
      "beta_elev", "beta_steep", "sigma", "nu_minus_two"};
      const std::array<Eigen::Index, 6> constrain_param_sizes__{1, 1, 
       1, 1, 1, 1};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = model2_student_t_model_namespace::model2_student_t_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return model2_student_t_model_namespace::profiles__;
}

#endif


