
// Code generated by stanc v2.29.0
#include <stan/model/model_header.hpp>
namespace prior_predictive_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 35> locations_array__ = 
{" (found before start of program)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 19, column 2 to column 13)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 20, column 2 to column 26)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 21, column 2 to column 26)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 22, column 2 to column 25)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 23, column 2 to column 27)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 24, column 2 to column 22)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 25, column 2 to column 19)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 27, column 2 to column 15)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 28, column 2 to column 25)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 29, column 2 to column 21)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 32, column 2 to column 33)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 33, column 2 to column 41)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 34, column 2 to column 41)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 35, column 2 to column 41)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 36, column 2 to column 43)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 37, column 2 to column 36)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 38, column 2 to column 29)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 41, column 4 to line 45, column 44)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 47, column 4 to column 54)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 48, column 4 to column 39)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 40, column 17 to line 49, column 3)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 40, column 2 to line 49, column 3)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 11, column 2 to column 17)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 12, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 12, column 2 to column 29)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 13, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 13, column 2 to column 30)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 14, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 14, column 2 to column 29)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 15, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 15, column 2 to column 26)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 27, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 28, column 9 to column 10)",
 " (in '/home/utmb_race_finish_times_bayesian_analysis/prior_predictive.stan', line 29, column 9 to column 10)"};




class prior_predictive_model final : public model_base_crtp<prior_predictive_model> {

 private:
  int N;
  Eigen::Matrix<double, -1, 1> distance_log_std__;
  Eigen::Matrix<double, -1, 1> elevation_log_std__;
  Eigen::Matrix<double, -1, 1> altitude_log_std__;
  Eigen::Matrix<double, -1, 1> steepness_std__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> distance_log_std{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> elevation_log_std{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> altitude_log_std{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> steepness_std{nullptr, 0};
 
 public:
  ~prior_predictive_model() { }
  
  inline std::string model_name() const final { return "prior_predictive_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.29.0", "stancflags = "};
  }
  
  
  prior_predictive_model(stan::io::var_context& context__,
                         unsigned int random_seed__ = 0,
                         std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "prior_predictive_model_namespace::prior_predictive_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 23;
      context__.validate_dims("data initialization","N","int",
           std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      
      
      current_statement__ = 23;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 24;
      stan::math::validate_non_negative_index("distance_log_std", "N", N);
      current_statement__ = 25;
      context__.validate_dims("data initialization","distance_log_std",
          "double", std::vector<size_t>{static_cast<size_t>(N)});
      distance_log_std__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&distance_log_std) Eigen::Map<Eigen::Matrix<double, -1, 1>>(distance_log_std__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> distance_log_std_flat__;
        current_statement__ = 25;
        distance_log_std_flat__ = context__.vals_r("distance_log_std");
        current_statement__ = 25;
        pos__ = 1;
        current_statement__ = 25;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 25;
          stan::model::assign(distance_log_std,
            distance_log_std_flat__[(pos__ - 1)],
            "assigning variable distance_log_std", stan::model::index_uni(sym1__));
          current_statement__ = 25;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 26;
      stan::math::validate_non_negative_index("elevation_log_std", "N", N);
      current_statement__ = 27;
      context__.validate_dims("data initialization","elevation_log_std",
          "double", std::vector<size_t>{static_cast<size_t>(N)});
      elevation_log_std__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&elevation_log_std) Eigen::Map<Eigen::Matrix<double, -1, 1>>(elevation_log_std__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> elevation_log_std_flat__;
        current_statement__ = 27;
        elevation_log_std_flat__ = context__.vals_r("elevation_log_std");
        current_statement__ = 27;
        pos__ = 1;
        current_statement__ = 27;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 27;
          stan::model::assign(elevation_log_std,
            elevation_log_std_flat__[(pos__ - 1)],
            "assigning variable elevation_log_std", stan::model::index_uni(sym1__));
          current_statement__ = 27;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 28;
      stan::math::validate_non_negative_index("altitude_log_std", "N", N);
      current_statement__ = 29;
      context__.validate_dims("data initialization","altitude_log_std",
          "double", std::vector<size_t>{static_cast<size_t>(N)});
      altitude_log_std__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&altitude_log_std) Eigen::Map<Eigen::Matrix<double, -1, 1>>(altitude_log_std__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> altitude_log_std_flat__;
        current_statement__ = 29;
        altitude_log_std_flat__ = context__.vals_r("altitude_log_std");
        current_statement__ = 29;
        pos__ = 1;
        current_statement__ = 29;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 29;
          stan::model::assign(altitude_log_std,
            altitude_log_std_flat__[(pos__ - 1)],
            "assigning variable altitude_log_std", stan::model::index_uni(sym1__));
          current_statement__ = 29;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 30;
      stan::math::validate_non_negative_index("steepness_std", "N", N);
      current_statement__ = 31;
      context__.validate_dims("data initialization","steepness_std","double",
           std::vector<size_t>{static_cast<size_t>(N)});
      steepness_std__ = 
        Eigen::Matrix<double, -1, 1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      new (&steepness_std) Eigen::Map<Eigen::Matrix<double, -1, 1>>(steepness_std__.data(), N);
        
      
      {
        std::vector<local_scalar_t__> steepness_std_flat__;
        current_statement__ = 31;
        steepness_std_flat__ = context__.vals_r("steepness_std");
        current_statement__ = 31;
        pos__ = 1;
        current_statement__ = 31;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 31;
          stan::model::assign(steepness_std,
            steepness_std_flat__[(pos__ - 1)],
            "assigning variable steepness_std", stan::model::index_uni(sym1__));
          current_statement__ = 31;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 32;
      stan::math::validate_non_negative_index("mu", "N", N);
      current_statement__ = 33;
      stan::math::validate_non_negative_index("log_time_rep", "N", N);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("time_rep", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 0U;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "prior_predictive_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "prior_predictive_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      double alpha = std::numeric_limits<double>::quiet_NaN();
      double beta_dist = std::numeric_limits<double>::quiet_NaN();
      double beta_elev = std::numeric_limits<double>::quiet_NaN();
      double beta_alt = std::numeric_limits<double>::quiet_NaN();
      double beta_steep = std::numeric_limits<double>::quiet_NaN();
      double sigma = std::numeric_limits<double>::quiet_NaN();
      double nu = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double, -1, 1> mu =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> log_time_rep =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> time_rep =
         Eigen::Matrix<double, -1, 1>::Constant(N,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 11;
      alpha = stan::math::normal_rng(stan::math::log(15), 1, base_rng__);
      current_statement__ = 12;
      beta_dist = stan::math::fabs(
                    stan::math::normal_rng(0.7, 0.4, base_rng__));
      current_statement__ = 13;
      beta_elev = stan::math::fabs(
                    stan::math::normal_rng(0.2, 0.3, base_rng__));
      current_statement__ = 14;
      beta_alt = stan::math::fabs(
                   stan::math::normal_rng(0.05, 0.1, base_rng__));
      current_statement__ = 15;
      beta_steep = stan::math::fabs(
                     stan::math::normal_rng(0.15, 0.2, base_rng__));
      current_statement__ = 16;
      sigma = stan::math::fabs(stan::math::normal_rng(0, 0.35, base_rng__));
      current_statement__ = 17;
      nu = (2 + stan::math::gamma_rng(2, 0.1, base_rng__));
      current_statement__ = 22;
      for (int i = 1; i <= N; ++i) {
        current_statement__ = 18;
        stan::model::assign(mu,
          ((((alpha +
               (beta_dist *
                 stan::model::rvalue(distance_log_std, "distance_log_std",
                   stan::model::index_uni(i)))) +
              (beta_elev *
                stan::model::rvalue(elevation_log_std, "elevation_log_std",
                  stan::model::index_uni(i)))) +
             (beta_alt *
               stan::model::rvalue(altitude_log_std, "altitude_log_std",
                 stan::model::index_uni(i)))) +
            (beta_steep *
              stan::model::rvalue(steepness_std, "steepness_std",
                stan::model::index_uni(i)))),
          "assigning variable mu", stan::model::index_uni(i));
        current_statement__ = 19;
        stan::model::assign(log_time_rep,
          stan::math::student_t_rng(nu,
            stan::model::rvalue(mu, "mu", stan::model::index_uni(i)), sigma,
            base_rng__),
          "assigning variable log_time_rep", stan::model::index_uni(i));
        current_statement__ = 20;
        stan::model::assign(time_rep,
          stan::math::exp(
            stan::model::rvalue(log_time_rep, "log_time_rep",
              stan::model::index_uni(i))),
          "assigning variable time_rep", stan::model::index_uni(i));
      }
      current_statement__ = 2;
      stan::math::check_greater_or_equal(function__, "beta_dist", beta_dist,
                                            0);
      current_statement__ = 3;
      stan::math::check_greater_or_equal(function__, "beta_elev", beta_elev,
                                            0);
      current_statement__ = 4;
      stan::math::check_greater_or_equal(function__, "beta_alt", beta_alt, 0);
      current_statement__ = 5;
      stan::math::check_greater_or_equal(function__, "beta_steep",
                                            beta_steep, 0);
      current_statement__ = 6;
      stan::math::check_greater_or_equal(function__, "sigma", sigma, 0);
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "nu", nu, 2);
      out__.write(alpha);
      out__.write(beta_dist);
      out__.write(beta_elev);
      out__.write(beta_alt);
      out__.write(beta_steep);
      out__.write(sigma);
      out__.write(nu);
      out__.write(mu);
      out__.write(log_time_rep);
      out__.write(time_rep);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_std_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"alpha", "beta_dist", "beta_elev",
      "beta_alt", "beta_steep", "sigma", "nu", "mu", "log_time_rep",
      "time_rep"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)},
      std::vector<size_t>{static_cast<size_t>(N)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "alpha");
      param_names__.emplace_back(std::string() + "beta_dist");
      param_names__.emplace_back(std::string() + "beta_elev");
      param_names__.emplace_back(std::string() + "beta_alt");
      param_names__.emplace_back(std::string() + "beta_steep");
      param_names__.emplace_back(std::string() + "sigma");
      param_names__.emplace_back(std::string() + "nu");
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_time_rep" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "time_rep" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "alpha");
      param_names__.emplace_back(std::string() + "beta_dist");
      param_names__.emplace_back(std::string() + "beta_elev");
      param_names__.emplace_back(std::string() + "beta_alt");
      param_names__.emplace_back(std::string() + "beta_steep");
      param_names__.emplace_back(std::string() + "sigma");
      param_names__.emplace_back(std::string() + "nu");
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "mu" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "log_time_rep" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "time_rep" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"beta_dist\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"beta_elev\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"beta_alt\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"beta_steep\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"nu\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_time_rep\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"time_rep\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"beta_dist\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"beta_elev\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"beta_alt\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"beta_steep\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"nu\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"mu\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_time_rep\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"},{\"name\":\"time_rep\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 0;
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + N) + N) + N);
      std::vector<double> vars_vec(num_params__
       + (emit_transformed_parameters * num_transformed)
       + (emit_generated_quantities * num_gen_quantities));
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        vars_vec.data(), vars_vec.size());
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 0;
      const size_t num_transformed = 0;
      const size_t num_gen_quantities = 
  (((((((((1 + 1) + 1) + 1) + 1) + 1) + 1) + N) + N) + N);
      vars.resize(num_params__
        + (emit_transformed_parameters * num_transformed)
        + (emit_generated_quantities * num_gen_quantities));
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 0> names__{};
      const std::array<Eigen::Index, 0> constrain_param_sizes__{};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = prior_predictive_model_namespace::prior_predictive_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return prior_predictive_model_namespace::profiles__;
}

#endif


